recipebook/ledger/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, add_image, add_recipe

urlpatterns = [
    path('recipes/list/', recipe_list, name ='recipe_list'),
    path('recipe/<int:recipe_id>/', recipe_detail, name='recipe_detail'),
    path('recipe/add/', add_recipe, name='add_recipe'),
    path('recipe/<int:pk>/add_image/', add_image, name='add_image'),

]

app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ledger/', include('ledger.urls', namespace="ledger")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/ledger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:ingredient_detail', args=[str(self.id)])
    
class Recipe(models.Model):
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default= "Unknown user")
    createdOn = models.DateTimeField(auto_now_add=True)
    updatedOn = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:recipe_detail', args=[str(self.id)])
    
class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=255)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='recipe')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

    def __str__(self):
        return f"{self.recipe.name}: {self.quantity} of {self.ingredient.name}"
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=255)

class RecipeImage(models.Model):
    image = models.ImageField(upload_to = 'images/', null = False)
    description = models.TextField(max_length=255)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return self.description

recipebook/ledger/forms.py
from django import forms
from .models import RecipeImage, Recipe

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = '__all__'

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'

recipebook/ledger/views.py
from django.shortcuts import render
from .models import Recipe, RecipeIngredient, RecipeImage
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import RecipeImageForm, RecipeForm

@login_required
def recipe_list(request):
    recipes = Recipe.objects.all()
    ctx = {'recipes': recipes}
    return render(request, 'ledger/recipe_list.html', ctx)

@login_required
def recipe_detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    ctx = {'recipe': recipe}
    return render(request, 'ledger/recipe_detail.html', ctx)

@login_required
def add_image(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    form = RecipeImageForm()
    if request.method == 'POST':
        form = RecipeImageForm(request.POST, request.FILES)
        if form.is_valid():
            i = RecipeImage()
            i.description = form.cleaned_data.get('description')
            i.image = form.cleaned_data.get('image')
            i.recipe = recipe
            i.save()
            return redirect('ledger:recipe_detail', recipe_id=recipe.pk)

    ctx = { 'form': form, 'recipe': recipe}
    return render(request, 'ledger/add_image.html', ctx)

@login_required
def add_recipe(request):
    form = RecipeForm()
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ledger:recipe_list')
    
    ctx = { 'form': form}
    return render(request, 'ledger/add_recipe.html', ctx)

recipebook/ledger/templates/ledger/add_image.html
{% extends "ledger/base.html" %}


{% block content %}
<h1> Add Image For "{{ recipe.name }}" </h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Image</button>
</form> 
{% endblock %}

recipebook/ledger/templates/ledger/add_recipe.html
{% extends "ledger/base.html" %}

{% block content %}
<h1> Add Recipe </h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Recipe</button>
</form> 
{% endblock %}

recipebook/ledger/templates/ledger/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Recipe Book{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    {% block styles %}{% endblock %}
</head>
<body>
    <header> 
        <h1>Recipe Book</h1>
        <div>
            {% if user.is_authenticated %}
                <form method="POST" action ="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            {% else %}
                <a href = "{% url 'login' %}"><button type="button">Login</button></a>
            {% endif %}
        </div>
    </header>


    <div id="content">
        {% block content %}{% endblock %}
        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

recipebook/ledger/templates/ledger/recipe_detail.html
{% extends "ledger/base.html" %}


{% block content %}
<h1> Author: {{recipe.author}} </h1>
<h2> {{ recipe.name }} </h2>
<ul>
    {% for image in recipe.images.all %}
    <img src="{{ image.image.url }}" alt="{{ image.description }}">
    {% endfor %}
</ul>
<ul>
    {% for ingredient in recipe.ingredients.all %}
    <li>{{ ingredient.quantity }} of {{ ingredient.ingredient.name }}</li>
    {% endfor %}
</ul>
<a href = "{% url 'ledger:add_image' recipe.pk%}">Add Image</a>
<footer>
    <a href = "{% url 'ledger:recipe_list'%}">Back To Recipe List</a>
</footer>

{% endblock %}

recipebook/ledger/templates/ledger/recipe_list.html
{% extends "ledger/base.html" %}

{% block title %} Recipes {% endblock %}
{% block content %}
<ul>
    {% for recipe in recipes %}
    <li><a href = "{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></li>
    {% endfor %}

    
</ul>
    <a href = "{% url 'ledger:add_recipe' %}">Add Recipe</a>
{% endblock %}

recipebook/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>